config:
  build: config
  volumes:
    - /etc/freetds
  env_file:
    - env.default
    - env.local
php:
  build: php
  ports:
   - "9000:9000"
  volumes:
    - ./site:/usr/share/nginx/html
  volumes_from:
    - config
  env_file:
    - env.default
    - env.local
nginx:
  build: nginx
  ports:
    - "80:80"
    - "443:443"
  links:
    - php
  volumes_from:
    - php
